# Generated by Django 4.1 on 2022-08-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=150)),
                ('mina', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=150)),
            ],
        ),
    ]
