# Generated by Django 4.1 on 2022-08-11 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
                ('valor', models.PositiveIntegerField(default=0)),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='modulo.modulomodel')),
            ],
        ),
    ]
